### ISSUE TITLE
Feature - Support add contest to google calendar 

### ISSUE THREAD

**Issue by sandeshShahapur** [AnanteshG/Contest-Hub#1]
Hey, nice work!

 I cloned the repo and implemented the title feature. If you are open to contributions, can you enable permissions for me to be able to push branches to the repo? I could then create a merge request

**Comment by AnanteshG** [comment]
Hey Sandesh!

Sure I'm open for contributions. Just create an issue and make a PR. I'll review it and merge it to the main branch.

**Comment by sandeshShahapur** [comment]
I needs da permissions to push my branch to this repo to be able to make a PR. I currently does not have da perms
![image](https://github.com/user-attachments/assets/fe995839-7a1a-43b9-a8a6-5fc2d33cb117)

**Comment by sandeshShahapur** [comment]
> I needs da permissions to push my branch to this repo to be able to make a PR. I currently does not have da perms ![image](https://private-user-images.githubusercontent.com/110241292/366943568-fe995839-7a1a-43b9-a8a6-5fc2d33cb117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODIxMDksIm5iZiI6MTcyNjI4MTgwOSwicGF0aCI6Ii8xMTAyNDEyOTIvMzY2OTQzNTY4LWZlOTk1ODM5LTdhMWEtNDNiOS1hOGE2LTVmYzJkMzNjYjExNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQwMjQzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmI2OTg5N2Q0MTgxYTAwMWExZjlkOThkODhiM2Y5ZGZjMzEwMDg4YTlkZjdhZmY4Y2ZjZDI3YTNjZTNkYzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cld7mrZ2Cx4k8nGraapY3MUsokioPpNQEBv_23yDXCs)

@AnanteshG ping

**Comment by AnanteshG** [comment]
Hey, Fork the repository and try making the pull request. It should work.

**Comment by sandeshShahapur** [comment]
> Hey, Fork the repository and try making the pull request. It should work.

my bad, forgor to fork 🤦‍♂️. i made a pull request
