### ISSUE TITLE
add example.env file

### ISSUE THREAD

**Issue by sandeshShahapur** [AnanteshG/Contest-Hub#4]
the url to fetch from contests is not provided. so when local hosting, the contests data is missing.

i observed the network tab in the browser and used this url: https://raw.githubusercontent.com/AnanteshG/ContestHub-backend/main/contests. but having an` example.env` file with the property  `VITE_API_URL` along with the url value people can use would be preferred

**Comment by AnanteshG** [comment]
Sure, I'll fix it.
